### ISSUE TITLE
ZeroMQ

### ISSUE THREAD

**Issue by nothingismagick** [feathersjs/primus#82]
Hi, I am a member of the dev-team at @quasarframework and am interested in knowing if there is a method you can recommend for using primus with ZeroMQ - because I am trying to write some websocket documentation and want to cover ALL the bases.

Happy to give you all the information I can

**Comment by daffl** [comment]
This module just contains the FeathersJS transport adapter for Primus. If you are asking about ZeroMQ support for Primus this is probably a better question for the [primus/primus repository](https://github.com/primus/primus).

**Comment by nothingismagick** [comment]
Ah, ok - thanks!!!
